language: python
cache: pip
python:
  - 3.5
  - 3.6
  - pypy3
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.8-dev
      dist: xenial
      sudo: required

script: make travis
install:
  - pip install .
  - pip install -r requirements.txt
after_success:
  - coveralls
